# Generated by Django 4.1 on 2022-09-12 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teacher", "0002_remove_teacher_courses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
