# Generated by Django 4.1 on 2022-09-23 04:35

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0006_page_postfilecontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", ckeditor.fields.RichTextField()),
                ("is_correct", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("published", models.BooleanField(default=True)),
                ("num", models.PositiveIntegerField()),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="In Progress",
                        max_length=20,
                    ),
                ),
                ("completed_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.CharField(max_length=6)),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "cater",
                    models.CharField(
                        choices=[
                            ("Typing Answer", "Typing Answer"),
                            ("One Choice", "One Choice"),
                            ("Multiple Answers", "Multiple Answers"),
                        ],
                        default="One Choice",
                        max_length=30,
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=6)),
                ("shuffle_ans", models.BooleanField(default=True)),
                ("is_1st_version", models.BooleanField(blank=True, default=True)),
                (
                    "fst_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="course.question",
                    ),
                ),
            ],
            options={"ordering": ["num"],},
        ),
        migrations.AlterField(
            model_name="postfilecontent",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="course.page",
            ),
        ),
        migrations.CreateModel(
            name="SubAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("showed_shuffle_ansIndex", models.CharField(max_length=25)),
                ("ans_text", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="course.attempt",
                    ),
                ),
                (
                    "chosen_answers",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="attempts",
                        to="course.answer",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="course.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("published", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=100)),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "cater",
                    models.CharField(
                        choices=[
                            ("Quiz", "Quiz"),
                            ("Class Exercise", "Class Exercise"),
                            ("Homework", "Homework"),
                            ("Exam", "Exam"),
                            ("Midterm", "Midterm"),
                            ("Midterm Exam", "Midterm Exam"),
                            ("Final Exam", "Final Exam"),
                        ],
                        default="Quiz",
                        max_length=30,
                    ),
                ),
                ("closed", models.BooleanField(default=True)),
                ("num_attempts", models.PositiveIntegerField(default=1, null=True)),
                ("time_limit", models.DurationField(null=True)),
                ("due_date", models.DateTimeField()),
                ("score", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "rule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Highest Attempt", "Highest Attempt"),
                            ("Latest Attempt", "Latest Attempt"),
                            ("Average of Attempts", "Average of Attempts"),
                        ],
                        default="Highest Attempt",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizzes",
                        to="course.module",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="course.quiz",
            ),
        ),
        migrations.AddField(
            model_name="attempt",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to="course.quiz",
            ),
        ),
        migrations.AddField(
            model_name="attempt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="course.question",
            ),
        ),
    ]
