# Generated by Django 4.1 on 2022-09-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_answer_attempt_question_alter_postfilecontent_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="num_attempts",
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="subattempt",
            name="chosen_answers",
            field=models.ManyToManyField(
                blank=True, related_name="attempts", to="course.answer"
            ),
        ),
    ]
