# Generated by Django 4.1 on 2022-09-23 10:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_alter_quiz_num_attempts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="content",
            field=ckeditor.fields.RichTextField(default=""),
        ),
    ]
