# Generated by Django 4.1 on 2022-09-25 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0009_alter_question_content"),
    ]

    operations = [
        migrations.AlterModelOptions(name="attempt", options={"ordering": ["num"]},),
    ]
