# Generated by Django 4.1 on 2022-09-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0010_alter_attempt_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subattempt",
            name="showed_shuffle_ansIndex",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
