# Generated by Django 4.1 on 2022-09-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0015_remove_submission_grade_remove_submission_quiz_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="point",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
