# Generated by Django 4.1 on 2022-10-25 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="message", name="author",),
        migrations.RemoveField(model_name="message", name="chat_room",),
        migrations.DeleteModel(name="Chat",),
        migrations.DeleteModel(name="Message",),
    ]
