# Generated by Django 4.1 on 2022-09-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_course_instructor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course", name="title", field=models.CharField(max_length=200),
        ),
    ]
