# Generated by Django 4.1 on 2022-09-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_notification_assocusernotice"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="from_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notices",
                to="app.course",
            ),
        ),
    ]
