# Generated by Django 4.1 on 2022-09-18 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_assocusernotice_date_created_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="AssocUserNotice",),
    ]
