# Generated by Django 4.1 on 2022-09-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_assocusernotice_options_leave"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="showed_on_inbox",
            field=models.CharField(default="sent a notice from", max_length=100),
        ),
    ]
