# Generated by Django 4.1 on 2022-09-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_notification_showed_on_inbox"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leave", old_name="course", new_name="from_course",
        ),
        migrations.RemoveField(model_name="notification", name="showed_on_inbox",),
        migrations.AddField(
            model_name="assocusernotice",
            name="role",
            field=models.CharField(
                choices=[
                    ("Notice", "Notice"),
                    ("Leave", "Leave"),
                    ("Feedback", "Feedback"),
                ],
                default="Notice",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assocusernotice",
            name="showed_on_inbox",
            field=models.CharField(default="sent a notice from", max_length=100),
        ),
    ]
