# Generated by Django 4.1 on 2022-09-20 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assocusernotice",
            name="role",
            field=models.CharField(
                choices=[
                    ("Notice", "Notice"),
                    ("Leave", "Leave"),
                    ("Feedback", "Feedback"),
                    ("Reply", "Reply"),
                ],
                default="Notice",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(max_length=2000)),
                ("pk_url", models.IntegerField(default=1)),
                (
                    "notice_assoc",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reply",
                        to="app.assocusernotice",
                    ),
                ),
                (
                    "on_feedback",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="app.feedback",
                    ),
                ),
                (
                    "on_the_reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="app.reply",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
