# Generated by Django 4.1 on 2022-09-21 23:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_alter_assocusernotice_role_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="pic",
            field=models.ImageField(
                default="media/course_pic/default.png", upload_to="media/course_pic"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="syllabus",
            field=ckeditor.fields.RichTextField(default="N/A"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reply",
            name="notice_assoc",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reply",
                to="app.assocusernotice",
            ),
        ),
    ]
