# Generated by Django 4.1 on 2022-10-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_course_pic_course_syllabus_alter_reply_notice_assoc"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="discount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=200, null=True),
        ),
    ]
