# Generated by Django 4.1 on 2022-10-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0004_remove_category_courses"),
        ("app", "0021_course_discount_course_price_course_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="categories",
            field=models.ManyToManyField(
                related_name="courses", to="commerce.category"
            ),
        ),
    ]
