# Generated by Django 4.1 on 2022-10-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapi", "0002_message"),
    ]

    operations = [
        migrations.AlterModelOptions(name="message", options={"ordering": ["-pk"]},),
        migrations.AddField(
            model_name="chat",
            name="roomName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
