# Generated by Django 4.1 on 2022-10-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_course_discount_course_price_course_slug"),
        ("commerce", "0002_rename_categories_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="courses",
            field=models.ManyToManyField(related_name="catergories", to="app.course"),
        ),
    ]
