# Generated by Django 4.1 on 2022-10-02 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0003_category_courses"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="courses",),
    ]
