# Generated by Django 4.1 on 2022-10-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0005_latestcourseview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="latestcourseview", options={"ordering": ["-order"]},
        ),
        migrations.AlterField(
            model_name="latestcourseview",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
