# Generated by Django 4.1 on 2022-10-02 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_course_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("commerce", "0007_alter_latestcourseview_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="latestcourseview",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_views",
                to="app.course",
            ),
        ),
        migrations.AlterField(
            model_name="latestcourseview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
