# Generated by Django 4.1 on 2022-10-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0009_cart_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
