# Generated by Django 4.1 on 2022-10-03 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_course_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("commerce", "0010_alter_cart_subtotal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=30)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("country", models.CharField(max_length=50)),
                ("street_address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("postcode", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=50)),
                ("additional_info", models.TextField(max_length=500)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Direct bank transfer", "Direct bank transfer"),
                            ("Check payments", "Check payments"),
                            ("PayPal", "PayPal"),
                        ],
                        default="Check payments",
                        max_length=20,
                    ),
                ),
                ("date_paid", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.PositiveIntegerField(default=1)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="app.course",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="commerce.order",
                    ),
                ),
            ],
            options={"ordering": ["num"],},
        ),
    ]
