# Generated by Django 4.1 on 2022-10-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0011_order_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="additional_info",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
